// Code generated by mockery v1.0.0. DO NOT EDIT.

package nft

import dragonchain "github.com/dragonchain/dragonchain-sdk-go"
import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// GetSmartContractObject provides a mock function with given fields: key, smartContractID
func (_m *MockClient) GetSmartContractObject(key string, smartContractID string) (*dragonchain.Response, error) {
	ret := _m.Called(key, smartContractID)

	var r0 *dragonchain.Response
	if rf, ok := ret.Get(0).(func(string, string) *dragonchain.Response); ok {
		r0 = rf(key, smartContractID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dragonchain.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, smartContractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
